application:
  version: 0.1.0
  title: Example using redis-cache and postgresSQL-Rest application
  owner: JeyCode
spring:
  profiles:
    active: standalone
---
logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
server:
  servlet:
    context-path: /red-pos-sam

spring:
  #  devtools.restart.enabled: true
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
  config:
    activate:
      on-profile: standalone
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/store-online-sample # dockerized
    username: ${application.owner}
    password: ${application.owner}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  #    show-sql: true
  cache:
    cache-names: users, orders, books
    ttl:
      books: 960
      users: 60
      orders: 20
    type: redis
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:32771}

mocks:
  books: 10000
  users: 100