application:
  version: 0.1.0
  title: Example using redis-cache and postgresSQL-Rest application
  owner: JeyCode
spring:
  profiles:
    active: standalone
---
server:
  servlet:
    context-path: /red-pos-sam
spring:
  config:
    activate:
      on-profile: standalone
