application:
  version: 0.1.0
  title: Example using redis-cache and postgresSQL-Rest application
  owner: JeyCode
spring:
  profiles:
    active: standalone
---
logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
server:
  servlet:
    context-path: /red-pos-sam
spring:
  config:
    activate:
      on-profile: standalone
  datasource:
    url: jdbc:postgresql://postgresDB:5432/store-online-sample
    username: jeycode
    password: jeycode
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  cache:
    cache-names: users, orders, books
    users:
      ttl: 30
    orders:
      ttl: 30
    books:
      ttl: 30
    type: redis
  redis:
    host: redis-cache
    port: 6379

mocks:
  books: 100
  users: 20