version: '3.8'
services:
  redis:
    image: 'redis:latest'
    container_name: redis
    restart: always
    command: redis-server --loglevel debug
    ports:
      - '6379'
    volumes:
      - 'redis-data:/data'
    environment:
      - REDIS_MAXMEMORY=30MB
      - REDIS_MAXCLIENTS=2
  postgresDB:
    image: 'postgres:latest'
    container_name: postgresDB
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=JeyCode
      - POSTGRES_PASSWORD=JeyCode
      - POSTGRES_DB=store-online-sample
    depends_on:
      - 'redis'
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'
  red-pos-sam-writer:
    image: 'red-pos-sam'
    container_name: red-pos-sam-writer
    ports:
      - '8080:8080'
    depends_on:
      - 'postgresDB'
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_HOST=postgresDB
  red-pos-sam-reader:
    image: 'red-pos-sam'
    container_name: red-pos-sam-reader
    ports:
      - '8081:8080'
    depends_on:
      - 'red-pos-sam-writer'
    environment:
      - INIT_DATA=true
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_HOST=postgresDB
volumes:
  redis-data:
  postgres-data: