version: '3.8'
services:
  redis:
    image: 'redis:latest'
    container_name: redis-cache
    ports:
      - '6379'
    volumes:
      - './data:/data'
  postgres-sql:
    image: 'postgres:latest'
    container_name: postgresDB
    volumes:
      - './postgres-data:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=jeycode
      - POSTGRES_PASSWORD=jeycode
      - POSTGRES_DB=store-sample
  red-pos-sam-writer:
    image: 'red-pos-sam'
    ports:
      - '8080:8080'
    depends_on:
      - redis
      - postgres-sql
  red-pos-sam-reader:
    image: 'red-pos-sam'
    ports:
      - '8081:8080'
    depends_on:
      - redis
      - postgres-sql
